apiVersion: v1
kind: Service
metadata:
  name: {{ template "ycommerce.backend" . }}
  labels:
    app: {{ template "ycommerce.name" . }}
    chart: {{ template "ycommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "ycommerce.name" . }}
    release: {{ .Release.Name }}
    group: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ycommerce.frontend" . }}
  labels:
    app: {{ template "ycommerce.name" . }}
    chart: {{ template "ycommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "ycommerce.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.backend.backendExclusive }}
    group: frontend
{{- end }}